### ISSUE TITLE
Se detiene la adquisición de datos de la estación D885 (Zapotillo)

### ISSUE THREAD

**Issue by lsantiago** [grissutpl/acelerometros#6]
@epduque Por correo se recibe la alerta de adquisición de datos:

> Grupo de Ingenieria Sismica y Sismologia
    Observatorio Sismico UTPL
    ---------------------------------------------
    Red de acelerografos UTPL
    Informe diario de adquisicion de datos

    Estado:

    - No existen datos de la estacion D885

El equipo deja de transmitir datos el 16 de febrero, su estado está al límite.

![image](https://user-images.githubusercontent.com/37159/219376307-1a73b13d-e469-4dce-8b54-c02a54139a01.png)

**Comment by lsantiago** [comment]
Hace algunos días atrás sucedió lo mismo, vuelve a funcionar si se envía las mismas configuraciones. El equipo no está grabando en el disco. 

![image](https://user-images.githubusercontent.com/37159/219376738-d99d6cfa-9cd7-4ecc-8083-d09a1287529f.png)

**Comment by epduque** [comment]
Al pesar en el lugar existe demasiada vibración, lo que hace que el equipo se sature.
Este es un punto que se debe considerar para una posible reubicación de la estación.

**Comment by lsantiago** [comment]
Lo de enviar nuevamente las configuraciones a la estación con la opción **Send to Das** solo dura entre 2 y 3 días, luego vuelve a detenerse la adquisición de datos. 

![image](https://user-images.githubusercontent.com/37159/221188126-1d29c61b-5c1b-4314-a395-d4a8bbb515e6.png)
